codecov:
  notify:
    require_ci_to_pass: true
comment: off
coverage:
  precision: 2
  range:
  - 50.0
  - 100.0
  round: down
  status:
    changes: false
    patch: false
    project: true
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
ignore:
    - "**/*mock*"
    - "/quilt-tester"
